/**
 * Auto-growing textareas; technique ripped from Facebook
 *
 * http://github.com/jaz303/jquery-grab-bag/tree/master/javascripts/jquery.autogrow-textarea.js
 */
(function($)
{
  $.fn.autogrow = function(options)
  {
    return this.filter('textarea').each(function()
    {
      var self         = this;
      var $self        = $(self);
      var minHeight    = $self.height();
      var noFlickerPad = $self.hasClass('autogrow-short') ? 0 : parseInt($self.css('lineHeight')) || 0;

      var shadow = $('<div></div>').css({
        position:    'absolute',
        top:         -10000,
        left:        -10000,
        width:       $self.width(),
        fontSize:    $self.css('fontSize'),
        fontFamily:  $self.css('fontFamily'),
        fontWeight:  $self.css('fontWeight'),
        lineHeight:  $self.css('lineHeight'),
        resize:      'none',
      'word-wrap': 'break-word'
      }).appendTo(document.body);

      var update = function(event)
      {
        var times = function(string, number)
        {
          for (var i=0, r=''; i<number; i++) r += string;
          return r;
        };

        var val = self.value.replace(/</g, '&lt;')
                  .replace(/>/g, '&gt;')
                  .replace(/&/g, '&amp;')
                  .replace(/\n$/, '<br/>&nbsp;')
                  .replace(/\n/g, '<br/>')
                  .replace(/ {2,}/g, function(space){ return times('&nbsp;', space.length - 1) + ' '; });

        // Did enter get pressed?  Resize in this keydown event so that the flicker doesn't occur.
        if (event && event.data && event.data.event === 'keydown' && event.keyCode === 13) {
          val += '<br />';
        }

        shadow.css('width', $self.width());
        shadow.html(val + (noFlickerPad === 0 ? '...' : '')); // Append '...' to resize pre-emptively.
        $self.height(Math.max(shadow.height() + noFlickerPad, minHeight));
      };

      $self.change(update).keyup(update).keydown({event:'keydown'},update);
      $(window).resize(update);

      update();
    });
  };
})(jQuery);

// quantize.js, Copyright 2012 Shao-Chung Chen.
// Licensed under the MIT license (http://www.opensource.org/licenses/mit-license.php)

// Basic CoffeeScript port of the (MMCQ) Modified Media Cut Quantization
// algorithm from the Leptonica library (http://www.leptonica.com/).
// Return a color map you can use to map original pixels to the reduced palette.
// 
// Rewritten from the JavaScript port (http://gist.github.com/1104622)
// developed by Nick Rabinowitz under the MIT license.

// Generated by CoffeeScript 1.3.3
var MMCQ, PriorityQueue;

PriorityQueue = (function() {

  function PriorityQueue(comparator) {
    this.comparator = comparator;
    this.contents = [];
    this.sorted = false;
  }

  PriorityQueue.prototype.sort = function() {
    this.contents.sort(this.comparator);
    return this.sotred = true;
  };

  PriorityQueue.prototype.push = function(obj) {
    this.contents.push(obj);
    return this.sorted = false;
  };

  PriorityQueue.prototype.peek = function(index) {
    if (index == null) {
      index = this.contents.length - 1;
    }
    if (!this.sorted) {
      this.sort();
    }
    return this.contents[index];
  };

  PriorityQueue.prototype.pop = function() {
    if (!this.sorted) {
      this.sort();
    }
    return this.contents.pop();
  };

  PriorityQueue.prototype.size = function() {
    return this.contents.length;
  };

  PriorityQueue.prototype.map = function(func) {
    return this.contents.map(func);
  };

  return PriorityQueue;

})();

MMCQ = (function() {
  var ColorBox, ColorMap, cboxFromPixels, getColorIndex, getHisto, medianCutApply,
    _this = this;

  MMCQ.sigbits = 5;

  MMCQ.rshift = 8 - MMCQ.sigbits;

  function MMCQ() {
    this.maxIterations = 1000;
    this.fractByPopulations = 0.75;
  }

  getColorIndex = function(r, g, b) {
    return (r << (2 * MMCQ.sigbits)) + (g << MMCQ.sigbits) + b;
  };

  ColorBox = (function() {

    function ColorBox(r1, r2, g1, g2, b1, b2, histo) {
      this.r1 = r1;
      this.r2 = r2;
      this.g1 = g1;
      this.g2 = g2;
      this.b1 = b1;
      this.b2 = b2;
      this.histo = histo;
    }

    ColorBox.prototype.volume = function(forced) {
      if (!this._volume || forced) {
        this._volume = (this.r2 - this.r1 + 1) * (this.g2 - this.g1 + 1) * (this.b2 - this.b1 + 1);
      }
      return this._volume;
    };

    ColorBox.prototype.count = function(forced) {
      var b, g, index, numpix, r, _i, _j, _k, _ref, _ref1, _ref2, _ref3, _ref4, _ref5;
      if (!this._count_set || forced) {
        numpix = 0;
        for (r = _i = _ref = this.r1, _ref1 = this.r2; _i <= _ref1; r = _i += 1) {
          for (g = _j = _ref2 = this.g1, _ref3 = this.g2; _j <= _ref3; g = _j += 1) {
            for (b = _k = _ref4 = this.b1, _ref5 = this.b2; _k <= _ref5; b = _k += 1) {
              index = getColorIndex(r, g, b);
              numpix += this.histo[index] || 0;
            }
          }
        }
        this._count_set = true;
        this._count = numpix;
      }
      return this._count;
    };

    ColorBox.prototype.copy = function() {
      return new ColorBox(this.r1, this.r2, this.g1, this.g2, this.b1, this.b2, this.histo);
    };

    ColorBox.prototype.average = function(forced) {
      var b, bsum, g, gsum, hval, index, mult, r, rsum, total, _i, _j, _k, _ref, _ref1, _ref2, _ref3, _ref4, _ref5;
      if (!this._average || forced) {
        mult = 1 << (8 - MMCQ.sigbits);
        total = 0;
        rsum = 0;
        gsum = 0;
        bsum = 0;
        for (r = _i = _ref = this.r1, _ref1 = this.r2; _i <= _ref1; r = _i += 1) {
          for (g = _j = _ref2 = this.g1, _ref3 = this.g2; _j <= _ref3; g = _j += 1) {
            for (b = _k = _ref4 = this.b1, _ref5 = this.b2; _k <= _ref5; b = _k += 1) {
              index = getColorIndex(r, g, b);
              hval = this.histo[index] || 0;
              total += hval;
              rsum += hval * (r + 0.5) * mult;
              gsum += hval * (g + 0.5) * mult;
              bsum += hval * (b + 0.5) * mult;
            }
          }
        }
        if (total) {
          this._average = [~~(rsum / total), ~~(gsum / total), ~~(bsum / total)];
        } else {
          this._average = [~~(mult * (this.r1 + this.r2 + 1) / 2), ~~(mult * (this.g1 + this.g2 + 1) / 2), ~~(mult * (this.b1 + this.b2 + 1) / 2)];
        }
      }
      return this._average;
    };

    ColorBox.prototype.contains = function(pixel) {
      var b, g, r;
      r = pixel[0] >> MMCQ.rshift;
      g = pixel[1] >> MMCQ.rshift;
      b = pixel[2] >> MMCQ.rshift;
      return ((this.r1 <= r && r <= this.r2)) && ((this.g1 <= g && g <= this.g2)) && ((this.b1 <= b && b <= this.b2));
    };

    return ColorBox;

  })();

  ColorMap = (function() {

    function ColorMap() {
      this.cboxes = new PriorityQueue(function(a, b) {
        var va, vb;
        va = a.count() * a.volume();
        vb = b.count() * b.volume();
        if (va > vb) {
          return 1;
        } else if (va < vb) {
          return -1;
        } else {
          return 0;
        }
      });
    }

    ColorMap.prototype.push = function(cbox) {
      return this.cboxes.push({
        cbox: cbox,
        color: cbox.average()
      });
    };

    ColorMap.prototype.palette = function() {
      return this.cboxes.map(function(cbox) {
        return cbox.color;
      });
    };

    ColorMap.prototype.size = function() {
      return this.cboxes.size();
    };

    ColorMap.prototype.map = function(color) {
      var i, _i, _ref;
      for (i = _i = 0, _ref = this.cboxes.size(); _i < _ref; i = _i += 1) {
        if (this.cboxes.peek(i).cbox.contains(color)) {
          return this.cboxes.peek(i).color;
        }
        return this.nearest(color);
      }
    };

    ColorMap.prototype.cboxes = function() {
      return this.cboxes;
    };

    ColorMap.prototype.nearest = function(color) {
      var dist, i, minDist, retColor, square, _i, _ref;
      square = function(n) {
        return n * n;
      };
      minDist = 1e9;
      for (i = _i = 0, _ref = this.cboxes.size(); _i < _ref; i = _i += 1) {
        dist = Math.sqrt(square(color[0] - this.cboxes.peek(i).color[0]) + square(color[1] - this.cboxes.peek(i).color[1]) + square(color[2] - this.cboxes.peek(i).color[2]));
        if (dist < minDist) {
          minDist = dist;
          retColor = this.cboxes.peek(i).color;
        }
      }
      return retColor;
    };

    return ColorMap;

  })();

  getHisto = function(pixels) {
    var b, g, histo, histosize, index, pixel, r, _i, _len;
    histosize = 1 << (3 * MMCQ.sigbits);
    histo = new Array(histosize);
    for (_i = 0, _len = pixels.length; _i < _len; _i++) {
      pixel = pixels[_i];
      r = pixel[0] >> MMCQ.rshift;
      g = pixel[1] >> MMCQ.rshift;
      b = pixel[2] >> MMCQ.rshift;
      index = getColorIndex(r, g, b);
      histo[index] = (histo[index] || 0) + 1;
    }
    return histo;
  };

  cboxFromPixels = function(pixels, histo) {
    var b, bmax, bmin, g, gmax, gmin, pixel, r, rmax, rmin, _i, _len;
    rmin = 1e6;
    rmax = 0;
    gmin = 1e6;
    gmax = 0;
    bmin = 1e6;
    bmax = 0;
    for (_i = 0, _len = pixels.length; _i < _len; _i++) {
      pixel = pixels[_i];
      r = pixel[0] >> MMCQ.rshift;
      g = pixel[1] >> MMCQ.rshift;
      b = pixel[2] >> MMCQ.rshift;
      if (r < rmin) {
        rmin = r;
      } else if (r > rmax) {
        rmax = r;
      }
      if (g < gmin) {
        gmin = g;
      } else if (g > gmax) {
        gmax = g;
      }
      if (b < bmin) {
        bmin = b;
      } else if (b > bmax) {
        bmax = b;
      }
    }
    return new ColorBox(rmin, rmax, gmin, gmax, bmin, bmax, histo);
  };

  medianCutApply = function(histo, cbox) {
    var b, bw, doCut, g, gw, index, lookaheadsum, maxw, partialsum, r, rw, sum, total, _i, _j, _k, _l, _m, _n, _o, _p, _q, _ref, _ref1, _ref10, _ref11, _ref12, _ref13, _ref14, _ref15, _ref16, _ref17, _ref2, _ref3, _ref4, _ref5, _ref6, _ref7, _ref8, _ref9;
    if (!cbox.count()) {
      return;
    }
    if (cbox.count() === 1) {
      return [cbox.copy()];
    }
    rw = cbox.r2 - cbox.r1 + 1;
    gw = cbox.g2 - cbox.g1 + 1;
    bw = cbox.b2 - cbox.b1 + 1;
    maxw = Math.max(rw, gw, bw);
    total = 0;
    partialsum = [];
    lookaheadsum = [];
    if (maxw === rw) {
      for (r = _i = _ref = cbox.r1, _ref1 = cbox.r2; _i <= _ref1; r = _i += 1) {
        sum = 0;
        for (g = _j = _ref2 = cbox.g1, _ref3 = cbox.g2; _j <= _ref3; g = _j += 1) {
          for (b = _k = _ref4 = cbox.b1, _ref5 = cbox.b2; _k <= _ref5; b = _k += 1) {
            index = getColorIndex(r, g, b);
            sum += histo[index] || 0;
          }
        }
        total += sum;
        partialsum[r] = total;
      }
    } else if (maxw === gw) {
      for (g = _l = _ref6 = cbox.g1, _ref7 = cbox.g2; _l <= _ref7; g = _l += 1) {
        sum = 0;
        for (r = _m = _ref8 = cbox.r1, _ref9 = cbox.r2; _m <= _ref9; r = _m += 1) {
          for (b = _n = _ref10 = cbox.b1, _ref11 = cbox.b2; _n <= _ref11; b = _n += 1) {
            index = getColorIndex(r, g, b);
            sum += histo[index] || 0;
          }
        }
        total += sum;
        partialsum[g] = total;
      }
    } else {
      for (b = _o = _ref12 = cbox.b1, _ref13 = cbox.b2; _o <= _ref13; b = _o += 1) {
        sum = 0;
        for (r = _p = _ref14 = cbox.r1, _ref15 = cbox.r2; _p <= _ref15; r = _p += 1) {
          for (g = _q = _ref16 = cbox.g1, _ref17 = cbox.g2; _q <= _ref17; g = _q += 1) {
            index = getColorIndex(r, g, b);
            sum += histo[index] || 0;
          }
        }
        total += sum;
        partialsum[b] = total;
      }
    }
    partialsum.forEach(function(d, i) {
      return lookaheadsum[i] = total - d;
    });
    doCut = function(color) {
      var cbox1, cbox2, count2, d2, dim1, dim2, i, left, right, _r, _ref18, _ref19;
      dim1 = color + '1';
      dim2 = color + '2';
      for (i = _r = _ref18 = cbox[dim1], _ref19 = cbox[dim2]; _r <= _ref19; i = _r += 1) {
        if (partialsum[i] > (total / 2)) {
          cbox1 = cbox.copy();
          cbox2 = cbox.copy();
          left = i - cbox[dim1];
          right = cbox[dim2] - i;
          if (left <= right) {
            d2 = Math.min(cbox[dim2] - 1, ~~(i + right / 2));
          } else {
            d2 = Math.max(cbox[dim1], ~~(i - 1 - left / 2));
          }
          while (!partialsum[d2]) {
            d2++;
          }
          count2 = lookaheadsum[d2];
          while (!count2 && partialsum[d2 - 1]) {
            count2 = lookaheadsum[--d2];
          }
          cbox1[dim2] = d2;
          cbox2[dim1] = cbox1[dim2] + 1;
          // console.log("cbox counts: " + (cbox.count()) + ", " + (cbox1.count()) + ", " + (cbox2.count()));
          return [cbox1, cbox2];
        }
      }
    };
    if (maxw === rw) {
      return doCut("r");
    }
    if (maxw === gw) {
      return doCut("g");
    }
    if (maxw === bw) {
      return doCut("b");
    }
  };

  MMCQ.prototype.quantize = function(pixels, maxcolors) {
    var cbox, cmap, histo, iter, pq, pq2,
      _this = this;
    if ((!pixels.length) || (maxcolors < 2) || (maxcolors > 256)) {
      console.log("invalid arguments");
      return false;
    }
    histo = getHisto(pixels);
    cbox = cboxFromPixels(pixels, histo);
    pq = new PriorityQueue(function(a, b) {
      var va, vb;
      va = a.count();
      vb = b.count();
      if (va > vb) {
        return 1;
      } else if (va < vb) {
        return -1;
      } else {
        return 0;
      }
    });
    pq.push(cbox);
    iter = function(lh, target) {
      var cbox1, cbox2, cboxes, ncolors, niters;
      ncolors = 1;
      niters = 0;
      while (niters < _this.maxIterations) {
        cbox = lh.pop();
        if (!cbox.count()) {
          lh.push(cbox);
          niters++;
          continue;
        }
        cboxes = medianCutApply(histo, cbox);
        cbox1 = cboxes[0];
        cbox2 = cboxes[1];
        if (!cbox1) {
          console.log("cbox1 not defined; shouldn't happen");
          return;
        }
        lh.push(cbox1);
        if (cbox2) {
          lh.push(cbox2);
          ncolors++;
        }
        if (ncolors >= target) {
          return;
        }
        if ((niters++) > _this.maxIterations) {
          console.log("infinite loop; perhaps too few pixels");
          return;
        }
      }
    };
    iter(pq, this.fractByPopulations * maxcolors);
    pq2 = new PriorityQueue(function(a, b) {
      var va, vb;
      va = a.count() * a.volume();
      vb = b.count() * b.volume();
      if (va > vb) {
        return 1;
      } else if (va < vb) {
        return -1;
      } else {
        return 0;
      }
    });
    while (pq.size()) {
      pq2.push(pq.pop());
    }
    iter(pq2, maxcolors - pq2.size());
    cmap = new ColorMap;
    while (pq2.size()) {
      cmap.push(pq2.pop());
    }
    return cmap;
  };

  return MMCQ;

}).call(this);

// Generated by CoffeeScript 1.6.3
(function() {
  window.ColorExtract = (function() {
    function ColorExtract() {}

    ColorExtract.getColorMap = function(canvas, sx, sy, w, h, nc) {
      var index, indexBase, pdata, pixels, x, y, _i, _j, _ref, _ref1;
      if (nc == null) {
        nc = 8;
      }
      pdata = canvas.getContext("2d").getImageData(sx, sy, w, h).data;
      pixels = [];
      for (y = _i = sy, _ref = sy + h; _i < _ref; y = _i += 1) {
        indexBase = y * w * 4;
        for (x = _j = sx, _ref1 = sx + w; _j < _ref1; x = _j += 1) {
          index = indexBase + (x * 4);
          pixels.push([pdata[index], pdata[index + 1], pdata[index + 2]]);
        }
      }
      return (new MMCQ).quantize(pixels, nc);
    };

    ColorExtract.colorDist = function(a, b) {
      var square;
      square = function(n) {
        return n * n;
      };
      return square(a[0] - b[0]) + square(a[1] - b[1]) + square(a[2] - b[2]);
    };

    ColorExtract.extract = function(image, canvas, callback) {
      var bgColor, bgColorMap, bgPalette, color, dist, fgColor, fgColor2, fgColorMap, fgPalette, maxDist, rgbToCssString, _i, _j, _len, _len1;
      canvas.width = 25;
      canvas.height = 25;
      canvas.getContext("2d").drawImage(image, 0, 0, canvas.width, canvas.height);
      bgColorMap = ColorExtract.getColorMap(canvas, 0, 0, canvas.width, canvas.height, 4);
      bgPalette = bgColorMap.cboxes.map(function(cbox) {
        return {
          count: cbox.cbox.count(),
          rgb: cbox.color
        };
      });
      bgPalette.sort(function(a, b) {
        return b.count - a.count;
      });
      bgColor = bgPalette[0].rgb;
      fgColorMap = ColorExtract.getColorMap(canvas, 0, 0, image.width, image.height, 10);
      fgPalette = fgColorMap.cboxes.map(function(cbox) {
        return {
          count: cbox.cbox.count(),
          rgb: cbox.color
        };
      });
      fgPalette.sort(function(a, b) {
        return b.count - a.count;
      });
      maxDist = 0;
      for (_i = 0, _len = fgPalette.length; _i < _len; _i++) {
        color = fgPalette[_i];
        dist = ColorExtract.colorDist(bgColor, color.rgb);
        if (dist > maxDist) {
          maxDist = dist;
          fgColor = color.rgb;
        }
      }
      maxDist = 0;
      for (_j = 0, _len1 = fgPalette.length; _j < _len1; _j++) {
        color = fgPalette[_j];
        dist = ColorExtract.colorDist(bgColor, color.rgb);
        if (dist > maxDist && color.rgb !== fgColor) {
          maxDist = dist;
          fgColor2 = color.rgb;
        }
      }
      rgbToCssString = function(color) {
        return "rgb(" + color[0] + ", " + color[1] + ", " + color[2] + ")";
      };
      return callback({
        bgColor: rgbToCssString(bgColor),
        fgColor: rgbToCssString(fgColor),
        fgColor2: rgbToCssString(fgColor2)
      });
    };

    return ColorExtract;

  })();

}).call(this);

/**
 * placeholder - HTML5 input placeholder polyfill
 * Copyright (c) 2012 DIY Co
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this
 * file except in compliance with the License. You may obtain a copy of the License at:
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF
 * ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 *
 * @author Brian Reavis <brian@thirdroute.com>
 */

(function($) {
  var NATIVE_SUPPORT = ('placeholder' in document.createElement('input'));
  var CSS_PROPERTIES = [
    '-moz-box-sizing', '-webkit-box-sizing', 'box-sizing',
    'padding-top', 'padding-right', 'padding-bottom', 'padding-left',
    'margin-top', 'margin-right', 'margin-bottom', 'margin-left',
    'border-top-width', 'border-right-width', 'border-bottom-width', 'border-left-width',
    'line-height', 'font-size', 'font-family', 'width', 'height',
    'top', 'left', 'right', 'bottom'
  ];

  var setupPlaceholder = function(input, options) {
    var i, evt, text, styles, zIndex, marginTop, dy, attrNode;
    var $input = $(input), $placeholder;

    try {
      attrNode = $input[0].getAttributeNode('placeholder');
      if (!attrNode) return;
      text = $input[0].getAttribute('placeholder');
      if (!text || !text.length) return;
      $input[0].setAttribute('placeholder', '');
      $input.data('placeholder', text);
    } catch (e) {
      return;
    }

    // enumerate textbox styles for mimicking
    styles = {};
    for (i = 0; i < CSS_PROPERTIES.length; i++) {
      styles[CSS_PROPERTIES[i]] = $input.css(CSS_PROPERTIES[i]);
    }
    zIndex = parseInt($input.css('z-index'), 10);
    if (isNaN(zIndex) || !zIndex) zIndex = 1;

    // create the placeholder
    $placeholder = $('<span>').addClass('placeholder').html(text);
    $placeholder.css(styles);
    $placeholder.css({
      'cursor': $input.css('cursor') || 'text',
      'display': 'block',
      'position': 'absolute',
      'overflow': 'hidden',
      'z-index': zIndex + 1,
      'background': 'none',
      'border-top-style': 'solid',
      'border-right-style': 'solid',
      'border-bottom-style': 'solid',
      'border-left-style': 'solid',
      'border-top-color': 'transparent',
      'border-right-color': 'transparent',
      'border-bottom-color': 'transparent',
      'border-left-color': 'transparent'
    });
    $placeholder.insertBefore($input);

    // compensate for y difference caused by absolute / relative difference (line-height factor)
    dy = $input.offset().top - $placeholder.offset().top;
    marginTop = parseInt($placeholder.css('margin-top'));
    if (isNaN(marginTop)) marginTop = 0;
    $placeholder.css('margin-top', marginTop + dy);

    // event handlers + add to document
    $placeholder.on('mousedown', function() {
      if (!$input.is(':enabled')) return;
      window.setTimeout(function(){
        $input.trigger('focus');
      }, 0);
    });

    function togglePlaceholderForInput() {
      $placeholder.toggle(!$.trim($input.val()).length);
    }

    $input.on('focus.placeholder', function() {
      $placeholder.hide();
    });
    $input.on('blur.placeholder', function() {
      togglePlaceholderForInput();
    });

    $input[0].onpropertychange = function() {
      if (event.propertyName === 'value') {
        togglePlaceholderForInput();
      }
    };

    $input.trigger('blur.placeholder');
  };

  // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

  $.fn.placeholder = function(options) {
    var $this = this;
    options = options || {};

    if (NATIVE_SUPPORT && !options.force) {
      return this;
    }

    window.setTimeout(function() {
      $this.each(function() {
        var tagName = this.tagName.toLowerCase();
        if (tagName === 'input' || tagName === 'textarea') {
          setupPlaceholder(this, options);
        }
      });
    }, 0);

    return this;
  };

})(jQuery);

'use strict';

/* Form placeholders */
(function($) {
  var EdicyFormPlaceholders = function(el) {
    this.$el = $(el);
    this.init();
  };

  EdicyFormPlaceholders.prototype = {
    init: function() {
      $('.form_field').each($.proxy(function(idx, field) {
        if ($(field).find('input[type="text"]').length > 0) {
          $(field).find('input[type="text"]').attr('placeholder', $(field).find('label').text());
          $(field).find('label').hide();
          if ($.fn.placeholder) {
            $(field).find('input[type="text"]').placeholder();
          }
        }
        if ($(field).find('textarea').length > 0) {
          $(field).find('textarea').attr('placeholder', $(field).find('label').text());
          $(field).find('label').hide();
          if ($.fn.placeholder) {
            $(field).find('textarea').placeholder();
          }
        }
      }, this));
    }
  };

  $.fn.edicyFormPlaceholders = function () {
    return this.each(function () {
      var data = $(this).data('edicyFormPlaceholders');
      if (!data) {
        $(this).data('edicyFormPlaceholders', new EdicyFormPlaceholders(this));
      }
    });
  };
})(jQuery);

/* General JS */
;(function($) {
  // ===========================================================================
  // Binds site search functionality.
  // ===========================================================================
  var bindSiteSearch = function(searchForm, languageCode, noResultsString) {
    if (searchForm) {
      var search = new VoogSearch(searchForm, {
        // This defines the number of results per query.
        per_page: 10,
        // Language code for restricting the search to page language.
        lang: languageCode,
        // If given, an DOM element results are rendered inside that element
        resultsContainer: $('.js-voog-search-modal-inner').get(0),
        // Defines if modal should close on sideclick.
        sideclick: true,
        // Mobile checkpoint
        mobileModeWidth: 640,
        // Updates results on every keypress.
        updateOnKeypress: true,
        // String for feedback if no results are found.
        noResults: noResultsString
      });
    }
  };

  var editmode = $('html').hasClass('editmode');

  // Remove comments if debouncing is used.
  // Function to limit the rate at which a function can fire.
  // var debounce = function(func, wait, immediate) {
  //   var timeout;
  //   return function() {
  //     var context = this, args = arguments;
  //     var later = function() {
  //       timeout = null;
  //       if (!immediate) func.apply(context, args);
  //     };
  //     var callNow = immediate && !timeout;
  //     clearTimeout(timeout);
  //     timeout = setTimeout(later, wait);
  //     if (callNow) func.apply(context, args);
  //   };
  // };

  var toggleFlags = function() {
    $('.js-option-toggle-flags').on('click', function(event) {
      event.stopPropagation();

      if ($(this).hasClass('js-flag-disable-btn')) {
        var flagsState = false;
      } else {
        var flagsState = true;
      }

      $(this).toggleClass('js-flag-disable-btn');
      $('body').toggleClass('flags-enabled flags-disabled');

      siteData.set("flags_state", flagsState);
    });
  };

  var bindFallbackHeaderLeftWidthCalculation = function() {
    var headerWidth = $('.js-header-inner').width(),
        headerRight = $('.js-header-right'),
        headerRightWidth = headerRight.width(),
        headerRightMargin = parseInt(headerRight.css('margin-left')) + 1;


    $('.js-header-left').css('min-width', headerWidth - headerRightWidth - headerRightMargin);
  };

  // TODO: Remove if Edicy is going to wrap table with the container
  var wrapTables = function() {
    if (!editmode) {
      $.each($('.content-formatted table'), function() {
        $(this).wrap('<div class="table-container"></div>');
      });
    }
  };

  var toggleMainMenu = function() {
    $('.js-menu-toggle').click(function() {
      $(this).toggleClass('open');
      $('.mobile-menu').toggleClass('expanded');
      if ($(this).hasClass('open')) {
        $('.js-search').addClass('hidden');
      } else {
        $('.js-search').removeClass('hidden');
      }
    });
  };

  var toggleLangMenu = function() {
    $('#lang-menu-toggle').click(function(event) {
      event.stopPropagation();
      $(this).toggleClass('open');
      $('#toggleable-lang-menu').toggleClass('expanded');
    });
    $('body').on('click', function(event) {
      var $t = $(event.target);
      if ($t.closest('.toggleable-lang-menu').length === 0 && !$t.is('#toggleable-lang-menu')) {
        $('#toggleable-lang-menu').removeClass('expanded');
        $('body').removeClass('voog-search-visible');
      }
      $('#lang-menu-toggle').removeClass('open');
    });
  };

  var handlePopoverMenuHide = function() {
    $('html').click(function(event) {
      var $t = $(event.target);
      if ($t.closest('.mobile-menu').length === 0 && $t.closest('.toggle-btn').length === 0) {
        if ($('.mobile-menu').hasClass('expanded')) {
          $('.mobile-menu').removeClass('expanded');
          $('.js-menu-toggle').removeClass('open');

          if (!$('.js-menu-toggle').hasClass('open')) {
            $('.js-search').removeClass('hidden');
          }
        }
      }
    });
  };

  var handleSearch = function() {
    $('.js-search-reset').click(function(event) {
      event.preventDefault();
      $('body').removeClass('voog-search-visible');
    });

    $('.js-search-open').click(function(event) {
      event.stopPropagation();
      $('body').addClass('voog-search-visible');
      $('.js-search-input').val('').focus();
    });

    $('.js-search-close').click(function(event) {
      $('body').removeClass('voog-search-visible');
    });

    $('.js-search-input').click(function(event) {
      event.stopPropagation();
    });

    $('.js-voog-search-modal-inner').click(function(event) {
      event.stopPropagation();
    });
  };

  var handleWindowResize = function() {
    // Add functions that should be trgiggered while resizing the window here.
    // Example:
    // $(window).resize(debounce(yourFunctionName, 3000));
  };

  // Returns the suitable version of the image depending on the viewport width.
  var getImageByWidth = function(sizes, targetWidth) {
    var prevImage;

    for (var i = 0, max = sizes.length; i < max; i++) {
      if (sizes[i].width < targetWidth) {
        return prevImage || sizes[i];
      }
      prevImage = sizes[i];
    }
    // Makes sure that smallest is returned if all images bigger than targetWidth.
    return sizes[sizes.length - 1];
  };

  var headerBgImageSizesContains = function(sizes, url) {
    for (var i = sizes.length; i--;) {
      if (url.indexOf(sizes[i].url.trim()) > -1) {
        return true;
      }
    }
    return false;
  };

  // Checks the lightness sum of header background image and color and sets the lightness class depending on it's value.
  var handleHeaderImageLightnessClass = function() {
    if (headerBgCombinedLightness >= 0.5) {
      $('.js-background-type').addClass('light-background').removeClass('dark-background');
    } else {
      $('.js-background-type').addClass('dark-background').removeClass('light-background');
    }
  };

  // Header background image and color preview logic function.
  var headerBgPreview = function(data, header) {
    // Defines the variables used in preview logic.

    var headerBgImagePrevious = $('.js-header-banner').css('background-image'),
        headerBgImageSuitable = data.imageSizes ? getImageByWidth(data.imageSizes, $(window).width()) : null,
        headerBgImage = (data.image && data.image !== '') ? 'url(' + headerBgImageSuitable.url + ')' : 'none',
        headerBgImageSizes = (data.imageSizes && data.imageSizes !== '') ? data.imageSizes : null,
        headerBgColor = (data.color && data.color !== '') ? data.color : 'rgba(0,0,0,0)',
        headerBgColorDataLightness = (data.colorData && data.colorData !== '') ? data.colorData.lightness : 1,
        colorExtractImage = $('<img>'),
        colorExtractCanvas = $('<canvas>'),
        colorExtractImageUrl = (data.image && data.image !== '') ? data.image : null;

    if (colorExtractImageUrl) {
      if (headerBgImageSizesContains(headerBgImageSizes, headerBgImagePrevious)) {
        headerBg.headerBgImageColor = headerBg.headerBgImageColor ? headerBg.headerBgImageColor : 'rgba(178,198,207,1)';
        headerBgCombinedLightness = getCombinedLightness(headerBg.headerBgImageColor, headerBgColor);
        handleHeaderImageLightnessClass();
      } else {
        colorExtractImage.attr('src', colorExtractImageUrl.replace(/.*\/(photos|voogstock)/g,'/photos'));
        colorExtractImage.on('load', function() {
          ColorExtract.extract(colorExtractImage[0], colorExtractCanvas[0], function(data) {
            headerBg.headerBgImageColor = data.bgColor ? data.bgColor : 'rgba(255,255,255,1)';
            headerBgCombinedLightness = getCombinedLightness(headerBg.headerBgImageColor, headerBgColor);
            handleHeaderImageLightnessClass();
          });
        });
      };
    } else {
      headerBg.headerBgImageColor = 'rgba(255,255,255,1)';
      headerBgCombinedLightness = getCombinedLightness(headerBg.headerBgImageColor, headerBgColor);
      handleHeaderImageLightnessClass();
    };

    // Updates the header background image and background color.
    $(header).css({'background-image' : headerBgImage});
    $(header).find('.background-color').css({'background-color' : headerBgColor});
  };

  // Header background image and color save logic function.
  var headerBgCommit = function(data, dataName) {
    var commitData = $.extend(true, {}, data);
    commitData.image = data.image || '';
    commitData.imageSizes = data.imageSizes || '';
    commitData.color = data.color || 'rgba(255,255,255,0)';
    commitData.combinedLightness = headerBgCombinedLightness;
    pageData.set(dataName, commitData);
  }

  var colorSum = function(bgColor, fgColor) {
    if (bgColor && fgColor) {
      if (typeof bgColor == 'string') {
        bgColor = bgColor.replace(/rgba?\(/,'').replace(/\)/,'').split(',');
        $.each(bgColor, function(n, x) {bgColor[n] = +x;});
      }
      if (typeof fgColor == 'string') {
        fgColor = fgColor.replace(/rgba?\(/,'').replace(/\)/,'').split(',');
        $.each(fgColor, function(n, x) {fgColor[n] = +x;});
      }
      if (typeof bgColor == 'object' && bgColor.hasOwnProperty('length')) {
        if (bgColor.length == 3) { bgColor.push(1.0); }
      }
      if (typeof fgColor == 'object' && fgColor.hasOwnProperty('length')) {
        if (fgColor.length == 3) { fgColor.push(1.0); }
      }
      var result = [0, 0, 0, 0];
      result[3] = 1 - (1 - fgColor[3]) * (1 - bgColor[3]);
      if (result[3] === 0) { result[3] = 1e-6; }
      result[0] = Math.min(fgColor[0] * fgColor[3] / result[3] + bgColor[0] * bgColor[3] * (1 - fgColor[3]) / result[3], 255);
      result[1] = Math.min(fgColor[1] * fgColor[3] / result[3] + bgColor[1] * bgColor[3] * (1 - fgColor[3]) / result[3], 255);
      result[2] = Math.min(fgColor[2] * fgColor[3] / result[3] + bgColor[2] * bgColor[3] * (1 - fgColor[3]) / result[3], 255);
      return $.map(result, function(e) { return Math.floor(e); });
    }
  };

  var getCombinedColor = function(bgColor, fgColor) {
    var sum = colorSum(bgColor || [255,255,255,1], fgColor || [255,255,255,1]);
    return sum;
  };

  var getCombinedLightness = function(bgColor, fgColor) {
    var combinedColor = getCombinedColor(bgColor, fgColor);
    var color = Math.round(((+combinedColor[0]) * 0.2126 + (+combinedColor[1]) * 0.7152 + (+combinedColor[2]) * 0.0722) / 2.55) / 100;
    return color;
  };

  var handleHeaderColorScheme = function(lightness) {
    if (typeof lightness != 'undefined') {
      if (lightness > 0.6) {
        $('.header-wrapper').addClass('light').removeClass('dark');
      } else {
        $('.header-wrapper').addClass('dark').removeClass('light');
      }
    }
  };

  var handlePostMinHeight = function() {
    $(window).ready(function(){
      $('.post').each(function(n, el) {
        var $post = $(el);
        var height = $post.find('.post-header').height();
        $post.find('.post-content').css('min-height', height);
      });
    });
  };

  var focusCommentsWithErrors = function() {
    $(document).ready(function() {
      if ($('.comment-form').hasClass('form_with_errors')) {
        $('html, body').scrollTop($('.comment-form').offset().top);
      } else if ($('form').find('.form_error, .form_notice').length > 0) {
        $('html, body').scrollTop($('.form_error, .form_notice').closest('form').offset().top);
      }
    });
  };

  // Initiations
  var initFrontPage = function(animation) {
    animation = typeof animation == 'undefined' ? false : animation;
    if (animation) {
      initStickyElements({
        stickyHeader: true,
        stickyMobileMenu: true,
        stickyFooter: false,
        stickyPostHeaders: false
      });
    }
  };
  var initCommonPage = function(animation) {
    animation = typeof animation == 'undefined' ? false : animation;
    if (animation) {
      initStickyElements({
        stickyHeader: true,
        stickyMobileMenu: true,
        stickyFooter: false,
        stickyPostHeaders: false
      });
    }
    if ($.fn.autogrow) {
      $('.form_field_textarea').autogrow();
    }
    $(window).ready(function() {
      if (!($.trim($('.content-header').get(0).innerHTML))) {
        $('.content-header').hide();
      }
    });
  };
  var initArticlePage = function(animation) {
    animation = typeof animation == 'undefined' ? false : animation;
    if (animation) {
      initStickyElements({
        stickyHeader: true,
        stickyMobileMenu: true,
        stickyFooter: false,
        stickyPostHeaders: false
      });
    }
    if ($.fn.autogrow) {
      $('.form_field_textarea').autogrow();
    }
  };
  var initBlogPage = function(animation) {
    animation = typeof animation == 'undefined' ? false : animation;
    if (animation) {
      initStickyElements({
        stickyHeader: true,
        stickyMobileMenu: true,
        stickyFooter: true,
        stickyPostHeaders: true
      });
    }
    handlePostMinHeight();
  };

  var initStickyElements = function(opts) {
    var stickyHeader = opts.stickyHeader || false,
    stickyMobileMenu = opts.stickyMobileMenu || false,
    stickyFooter = opts.stickyFooter || false,
    stickyPostHeaders = opts.stickyPostHeaders || false,
    startScroll,
    endScroll,
    scrolled,
    container = $('.container'),
    header = $('.header'),
    footer = $('.footer'),
    headerStaticArea = $(header).height() + 90,
    footerStaticArea = $(footer).height() + 90,
    footerExpandTimeout,
    latestKnownScrollY = 0,
    ticking = false;

    var getPostHeights = function () {
      var posts = $('.post'),
      heights = [];
      posts.each(function(n, el) {
        heights.push(el.getBoundingClientRect().top);
      });
      return heights;
    };

    var handler = function (postHeights) {
      if (!startScroll) {
        startScroll = $(window).scrollTop();
      } else {
        endScroll = $(window).scrollTop();
        scrolled = endScroll - startScroll;
        if (window.innerWidth < 640 && stickyMobileMenu) {
          if (scrolled > 5 && startScroll > headerStaticArea) {
            $('.topbar').addClass('fixed').css({'top' : -headerStaticArea});
          } else if (scrolled < -5 && startScroll > headerStaticArea) {
            $('.topbar').addClass('fixed').css({'top' : 0});
          } else if (scrolled < 0 && startScroll <= 100 && $('.topbar').hasClass('fixed') === true) {
            $(container).css({'margin-top' : 0});
            $('.topbar').removeClass('fixed');
          }
        }
        if (window.innerWidth > 640 && stickyFooter) {
          if ($('.post').eq(0).offset().top - $(window).innerHeight() + 90 < $(document).scrollTop()) {
            if (startScroll + window.innerHeight <= $(document).height() - footerStaticArea - 40) {
              // above footer
              if (scrolled < -5) {
                fixFooter(false);
              // down and above footer
            } else if (scrolled > 5) {
              hideFooter();
            }
          } else {
              // down and below footer + 90px
              resetFooter();
            }
          } else {
            resetFooter();
          }
        }
        if (stickyHeader && $(header).find('.header-inner').height() < 60) {
          // Scrolling down and offset is larger than
          if (scrolled > 5 && startScroll > headerStaticArea) {
            hideHeader();

          // Up and fixed area
        } else if (scrolled < -5 && startScroll > headerStaticArea) {
          fixHeader();
          setTimeout(function() {
            if ($(window).scrollTop() <= headerStaticArea) {
              resetHeader();
            }
          }, 20);

          // Up, static area and header is fixed
        } else if (scrolled < -5 && startScroll <= headerStaticArea) {
          resetHeader();
        }
      }
      startScroll = 0;
    }
    if (window.innerWidth > 640 && stickyPostHeaders) {
      $('.post').each(function(n, el) {
        var offset = 30,
        $header = $(el).find('.post-header'),
        topBoundary = 0 + offset,
        bottomBoundary = -($(el).height() - offset - $header.height());

          // scroll is between top and bottom of the .post
          if (postHeights[n] < topBoundary) {
            // scroll is inside .post
            if (postHeights[n] > bottomBoundary) {
              $header.removeClass('top bottom');
              $(el).addClass('fixed-header');
            // scroll is below .post
          } else {
            $header.addClass('bottom').removeClass('top');
            $(el).removeClass('fixed-header');
          }
          // scroll is above .post
        } else {
          $header.addClass('top').removeClass('bottom');
          $(el).removeClass('fixed-header');
        }
      });
    }
  };

  var hideHeader = function() {
    $(header).addClass('header-fixed').css({'top' : -headerStaticArea});
    $(container).css({'padding-top' : headerStaticArea});
  };

  var fixHeader = function() {
    var headerOffset;

    if ($('body').hasClass('edy-checkout-button-visible')) {
      headerOffset = $('.edy-ecommerce-shopping-cart-button').outerHeight();
    } else {
      headerOffset = 0;
    }

    $(header).addClass('header-fixed header-animated').css({'top' : headerOffset});

    $(container).css({'padding-top' : headerStaticArea});
  };

  var resetHeader = function() {
    $(header).removeClass('header-fixed header-animated');
    $(container).css({'padding-top' : 0});
    $('.post.fixed-header').removeClass('fixed-header');
  };

  var hideFooter = function() {
    $(footer).addClass('footer-fixed footer-animated footer-hidden');
    $(footer).css('bottom', -$(footer).outerHeight());
  };

  var resetFooter = function() {
    $(footer).removeClass('footer-fixed footer-animated footer-hidden');
    $('body').removeClass('voog-search-visible');
    $(footer).css({'bottom': '', 'left': '' });
    $(container).css({'margin-bottom' : ''});
  };

  var fixFooter = function(expanded) {
    expanded = expanded || false;
    $(footer).addClass('footer-fixed footer-animated');
    $(footer).css({
      'left' : $('.container').offset().left,
      'bottom': (expanded ? 0 : (-$(footer).height() + 60))
    });
    $(container).css({'margin-bottom' : footerStaticArea});
  };

  var expandFooter = function(expand) {
    if (expand) {
      if ($(footer).hasClass('footer-fixed')) {
        clearTimeout(footerExpandTimeout);
        fixFooter(true);
        $('footer .gradient-overlay').hide();
      }
    } else {
      if ($('footer').hasClass('footer-fixed')) {
        footerExpandTimeout = setTimeout(function() {
          fixFooter(false);
          $('footer .gradient-overlay').show();
        }, 1500);
      }
    }
  };

  var onScroll = function() {
    latestKnownScrollY = window.scrollY;
    requestTick();
  };

  var requestTick = function() {
    if (!ticking) { requestAnimationFrame(update); }
    ticking = true;
  };

  var update = function() {
    ticking = false;
    // NOTE: Animated header on mobile screen is too buggy. To fix it a huge
    // refactor is needed. Disableing it is a quicker and less painful method.
    if ($(window).width() > 640) {
      handler(getPostHeights());
    }
  };

  $(window).on('load resize', function() {
    // NOTE: Animated header on mobile screen is too buggy. To fix it a huge
    // refactor is needed. Disableing it is a quicker and less painful method.
    if ($(window).width() > 640) {
      handler(getPostHeights());
    } else {
      $('.container').css({
        'padding-top': '',
        'margin-bottom': ''
      });

      $('.header-fixed').removeClass('header-fixed header-animated').css('top', '');
    }
  }).on('scroll', onScroll);

  $('footer').bind('mouseenter', function() {
    expandFooter(true);
  }).bind('mouseleave', function() {
    expandFooter(false);
  });
};

var bindCustomTexteditorStyles = function(buttonTranslation) {
  window.edy = window.edy || [];
  edy.push(['texteditorStyles', {name: buttonTranslation, tagname:'a', attribute: {'href': '#'}, classname: 'custom-btn', toggle: true}]);
};

var init = function() {
  toggleMainMenu();
  toggleLangMenu();
  handlePopoverMenuHide();
  handleWindowResize();
  handleSearch();
  wrapTables();
  focusCommentsWithErrors();

  $('.content form').edicyFormPlaceholders();

  if (!Modernizr.flexbox && editmode) {
    bindFallbackHeaderLeftWidthCalculation();
  };
};

// ===========================================================================
  // Sets functions that will be initiated on items list layouts.
  // ===========================================================================
  var initItemsPage = function() {
    if (!editmode()) {
      bindContentItemImageLazyload();
    }
  };

// ===========================================================================
  // Toggles product categories visibility in main menu.
  // ===========================================================================
  var bindRootItemSettings = function(rootItemValuesObj) {
    if (!('show_product_related_pages_in_main_menu' in rootItemValuesObj)) {
      rootItemValuesObj.show_product_related_pages_in_main_menu = false;
    }

    $('.js-root-item-settings-toggle').each(function(index, languageMenuSettingsButton) {
      var rootItemSettingsEditor = new Edicy.SettingsEditor(languageMenuSettingsButton, {
        menuItems: [
          {
            "titleI18n": "show_in_main_menu",
            "type": "checkbox",
            "key": "show_product_related_pages_in_main_menu",
            "states": {
              "on": true,
              "off": false
            }
          }
        ],

        buttonTitleI18n: "settings",

        values: rootItemValuesObj,

        containerClass: ['js-root-item-settings-popover', 'js-prevent-sideclick'],

        preview: function(data) {
          if (!data.show_product_related_pages_in_main_menu === true) {
            $('.js-menu-item-products').addClass('is-hidden');
          } else {
            $('.js-menu-item-products').removeClass('is-hidden');
          }
        },

        commit: function(data) {
          siteData.set('settings_root_item', data);
        }
      });
    });
  };

// ===========================================================================
  // Binds editmode image drop areas.
  // ===========================================================================
  var bindContentItemImgDropAreas = function(placeholderText) {
    $('.js-content-item-img-drop-area').each(function(index, imgDropAreaTarget) {
      var $imgDropAreaTarget = $(imgDropAreaTarget),
          $contentItemBox = $imgDropAreaTarget.closest('.js-content-item-box'),
          itemId = $contentItemBox.data('item-id'),
          itemType = $contentItemBox.data('item-type'),
          itemData = new Edicy.CustomData({
            type: itemType,
            id: itemId
          });

      var imgDropArea = new Edicy.ImgDropArea($imgDropAreaTarget, {
        positionable: false,
        target_width: 1280,
        placeholder: '<div class="edy-img-drop-area-placeholder">' + placeholderText + '</div>',
        removeBtn: '<div class="edy-img-drop-area-remove-image">' +
                      '<div class="edy-img-drop-area-remove-image-ico">' +
                        '<svg width="16" height="20" viewBox="0 0 26 30" xmlns="http://www.w3.org/2000/svg">' +
                          '<g fill-rule="nonzero" fill="currentColor">' +
                            '<g transform="translate(2 5)">' +
                              '<path d="M0 .997h2V21c0 1 1 2 2 2h14c1 0 2-1 2-2V1h2v20c0 2.25-1.75 4-4 4H4c-2.25 0-4-1.75-4-4V.997z"/>' +
                              '<rect x="10" y="4" width="2" height="16" rx="1"/>' +
                              '<rect x="5" y="4" width="2" height="16" rx="1"/>' +
                              '<rect x="15" y="4" width="2" height="16" rx="1"/>' +
                            '</g>' +
                            '<path d="M26 4v2H0V4h7V2c0-1 1-2 2-2h8c1 0 2 1 2 2v2h7zM9 4h8V3c0-.5-.5-1-1-1h-6c-.5 0-1 .5-1 1v1z"/>' +
                          '</g>' +
                        '</svg>' +
                      '</div>' +
                    '</div>',

        change: function(data) {
          var imageId;

          $imgDropAreaTarget
            .removeClass('is-cropped')
            .addClass('not-cropped')
            .css('opacity', .1)
          ;

          if (data) {
            imageId = data.original_id;

            $contentItemBox
              .removeClass('without-image is-loaded with-error')
              .addClass('with-image not-loaded')
            ;

            setImageOrientation($contentItemBox, data.width, data.height);
          } else {
            imageId = null;

            $contentItemBox
              .removeClass('with-image is-loaded with-error')
              .addClass('without-image not-loaded')
            ;

            $contentItemBox.find('.edy-img-drop-area-placeholder').css('opacity', 0);
          }

          setItemImage($contentItemBox, $imgDropAreaTarget, itemId, imageId, itemType);
        }
      });
    });
  };

  var setImageOrientation = function($contentItemBox, width, height) {
    var $imgDropAreaTarget = $contentItemBox.find('.js-content-item-img-drop-area'),
        $cropToggleButton = $contentItemBox.find('.js-toggle-crop-state');

    if (width > height) {
      $imgDropAreaTarget
        .removeClass('image-landscape image-square image-portrait')
        .addClass('image-landscape')
      ;
    } else if (width === height) {
      $imgDropAreaTarget
        .removeClass('image-landscape image-square image-portrait')
        .addClass('image-square')
      ;
    } else {
      $imgDropAreaTarget
        .removeClass('image-landscape image-square image-portrait')
        .addClass('image-portrait')
      ;
    }

    if ($imgDropAreaTarget.hasClass('image-square')) {
      $cropToggleButton
        .removeClass('is-visible')
        .addClass('is-hidden')
      ;
    } else {
      $cropToggleButton
        .removeClass('is-hidden')
        .addClass('is-visible')
      ;
    }
  };

  var setItemImage = function($contentItemBox, $imgDropArea, itemId, imageId, itemType) {
    var apiType = itemType === 'article' ? 'articles' : 'pages',
        itemData = new Edicy.CustomData({
          type: itemType,
          id: itemId
        });

    $.ajax({
       type: 'PATCH',
       contentType: 'application/json',
       url: '/admin/api/' + apiType +'/' + itemId,
       data: JSON.stringify({'image_id': imageId}),
       dataType: 'json',
       success: function(data) {
         itemData.set('image_crop_state', 'not-cropped');
         $contentItemBox.removeClass('not-loaded with-error').addClass('is-loaded');
         $contentItemBox.find('.edy-img-drop-area-placeholder').css('opacity', 1);
         $imgDropArea.css('opacity', 1);
       },
       timeout: 30000,
       error: function(data) {
         $contentItemBox.removeClass('not-loaded is-loaded with-error').addClass('with-error');
       }
    });
  };

  // ===========================================================================
  // Sets functions that will be initiated globally when resizing the browser
  // window.
  // ===========================================================================
  var bindContentItemImageCropToggle = function() {
    $('.js-toggle-crop-state').on('click', function() {
      var $contentItemBox = $(this).closest('.js-content-item-box'),
          $imgDropAreaTarget = $contentItemBox.find('.js-content-item-img-drop-area'),
          itemId = $contentItemBox.data('item-id'),
          itemType = $contentItemBox.data('item-type'),
          itemData = new Edicy.CustomData({
            type: itemType,
            id: itemId
          }),
          imageCropState;

      if ($imgDropAreaTarget.hasClass('is-cropped')) {
        $imgDropAreaTarget
          .removeClass('is-cropped')
          .addClass('not-cropped')
        ;

        imageCropState = 'not-cropped';
      } else {
        $imgDropAreaTarget
          .removeClass('not-cropped')
          .addClass('is-cropped')
        ;

        imageCropState = 'is-cropped';
      }

      itemData.set('image_crop_state', imageCropState);
    });
  };

  // ===========================================================================
  // Load article cover images only when they are close or appearing in the
  // viewport.
  // ===========================================================================
  var bindContentItemImageLazyload = function() {
    $(document).ready(function() {
      setTimeout(function() {
        $('.js-content-item-box').addClass('not-loaded');
      }, 3000);
    });

    $('.js-lazyload').lazyload({
      threshold : 500,
      effect : "fadeIn",
      placeholder: 'data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==',

      load: function() {
        var $contentItemBox = $(this).closest('.js-content-item-box');

        $contentItemBox.removeClass('not-loaded with-error').addClass('is-loaded');

        setTimeout(function() {
          $contentItemBox.removeClass('not-loaded with-error');
          $contentItemBox.find('.js-loader').remove();
        }, 3000);
      }
    });
  };

  // ===========================================================================
  // Function to detect if site is displayed in editmode.
  // ===========================================================================
  var editmode = function () {
    return $('html').hasClass('editmode');
  };

  // ===========================================================================
  // Sets header menu initial width attribute for menu mode calculation.
  // ===========================================================================
  var setHeaderMenuInitialWidth = function() {
    var $headerMenu = $('.js-header-menu');

    $headerMenu.attr('data-initial-width', $headerMenu.outerWidth(true));
  };

  // Enables the usage of the initiations outside this file.
  // For example add "<script>site.initBlogPage();</script>" at the end of the "Blog & News" page to initiate blog listing view functions.

window.site = $.extend(window.site || {}, {
  initFrontPage: initFrontPage,
  initCommonPage: initCommonPage,
  initBlogPage: initBlogPage,
  initArticlePage: initArticlePage,
  toggleFlags: toggleFlags,
  getImageByWidth: getImageByWidth,
  headerBgPreview: headerBgPreview,
  headerBgCommit: headerBgCommit,
  initItemsPage: initItemsPage,
  handleHeaderColorScheme: handleHeaderColorScheme,
  bindCustomTexteditorStyles: bindCustomTexteditorStyles,
  bindRootItemSettings: bindRootItemSettings,
  bindContentItemImgDropAreas: bindContentItemImgDropAreas,
  bindContentItemImageCropToggle: bindContentItemImageCropToggle,
  bindSiteSearch: bindSiteSearch
});

init();
})(jQuery);

"use strict";!function(e){var t=function(t){this.$el=e(t),this.init()};t.prototype={init:function(){e(".form_field").each(e.proxy(function(t,o){e(o).find('input[type="text"]').length>0&&(e(o).find('input[type="text"]').attr("placeholder",e(o).find("label").text()),e(o).find("label").hide(),e.fn.placeholder&&e(o).find('input[type="text"]').placeholder()),e(o).find("textarea").length>0&&(e(o).find("textarea").attr("placeholder",e(o).find("label").text()),e(o).find("label").hide(),e.fn.placeholder&&e(o).find("textarea").placeholder())},this))}},e.fn.edicyFormPlaceholders=function(){return this.each(function(){e(this).data("edicyFormPlaceholders")||e(this).data("edicyFormPlaceholders",new t(this))})}}(jQuery),function(e){var t=function(t,o,a){if(t){new VoogSearch(t,{per_page:10,lang:o,resultsContainer:e(".js-voog-search-modal-inner").get(0),sideclick:!0,mobileModeWidth:640,updateOnKeypress:!0,noResults:a})}},o=e("html").hasClass("editmode"),a=function(){e(".js-option-toggle-flags").on("click",function(t){if(t.stopPropagation(),e(this).hasClass("js-flag-disable-btn"))var o=!1;else var o=!0;e(this).toggleClass("js-flag-disable-btn"),e("body").toggleClass("flags-enabled flags-disabled"),siteData.set("flags_state",o)})},i=function(){var t=e(".js-header-inner").width(),o=e(".js-header-right"),a=o.width(),i=parseInt(o.css("margin-left"))+1;e(".js-header-left").css("min-width",t-a-i)},s=function(){o||e.each(e(".content-formatted table"),function(){e(this).wrap('<div class="table-container"></div>')})},n=function(){e(".js-menu-toggle").click(function(){e(this).toggleClass("open"),e(".mobile-menu").toggleClass("expanded"),e(this).hasClass("open")?e(".js-search").addClass("hidden"):e(".js-search").removeClass("hidden")})},r=function(){e("#lang-menu-toggle").click(function(t){t.stopPropagation(),e(this).toggleClass("open"),e("#toggleable-lang-menu").toggleClass("expanded")}),e("body").on("click",function(t){var o=e(t.target);0!==o.closest(".toggleable-lang-menu").length||o.is("#toggleable-lang-menu")||(e("#toggleable-lang-menu").removeClass("expanded"),e("body").removeClass("voog-search-visible")),e("#lang-menu-toggle").removeClass("open")})},d=function(){e("html").click(function(t){var o=e(t.target);0===o.closest(".mobile-menu").length&&0===o.closest(".toggle-btn").length&&e(".mobile-menu").hasClass("expanded")&&(e(".mobile-menu").removeClass("expanded"),e(".js-menu-toggle").removeClass("open"),e(".js-menu-toggle").hasClass("open")||e(".js-search").removeClass("hidden"))})},l=function(){e(".js-search-reset").click(function(t){t.preventDefault(),e("body").removeClass("voog-search-visible")}),e(".js-search-open").click(function(t){t.stopPropagation(),e("body").addClass("voog-search-visible"),e(".js-search-input").val("").focus()}),e(".js-search-close").click(function(t){e("body").removeClass("voog-search-visible")}),e(".js-search-input").click(function(e){e.stopPropagation()}),e(".js-voog-search-modal-inner").click(function(e){e.stopPropagation()})},c=function(e,t){for(var o,a=0,i=e.length;a<i;a++){if(e[a].width<t)return o||e[a];o=e[a]}return e[e.length-1]},g=function(e,t){for(var o=e.length;o--;)if(t.indexOf(e[o].url.trim())>-1)return!0;return!1},h=function(){headerBgCombinedLightness>=.5?e(".js-background-type").addClass("light-background").removeClass("dark-background"):e(".js-background-type").addClass("dark-background").removeClass("light-background")},m=function(t,o){var a=e(".js-header-banner").css("background-image"),i=t.imageSizes?c(t.imageSizes,e(window).width()):null,s=t.image&&""!==t.image?"url("+i.url+")":"none",n=t.imageSizes&&""!==t.imageSizes?t.imageSizes:null,r=t.color&&""!==t.color?t.color:"rgba(0,0,0,0)",d=(t.colorData&&""!==t.colorData&&t.colorData.lightness,e("<img>")),l=e("<canvas>"),m=t.image&&""!==t.image?t.image:null;m?g(n,a)?(headerBg.headerBgImageColor=headerBg.headerBgImageColor?headerBg.headerBgImageColor:"rgba(178,198,207,1)",headerBgCombinedLightness=C(headerBg.headerBgImageColor,r),h()):(d.attr("src",m.replace(/.*\/(photos|voogstock)/g,"/photos")),d.on("load",function(){ColorExtract.extract(d[0],l[0],function(e){headerBg.headerBgImageColor=e.bgColor?e.bgColor:"rgba(255,255,255,1)",headerBgCombinedLightness=C(headerBg.headerBgImageColor,r),h()})})):(headerBg.headerBgImageColor="rgba(255,255,255,1)",headerBgCombinedLightness=C(headerBg.headerBgImageColor,r),h()),e(o).css({"background-image":s}),e(o).find(".background-color").css({"background-color":r})},f=function(t,o){var a=e.extend(!0,{},t);a.image=t.image||"",a.imageSizes=t.imageSizes||"",a.color=t.color||"rgba(255,255,255,0)",a.combinedLightness=headerBgCombinedLightness,pageData.set(o,a)},u=function(t,o){if(t&&o){"string"==typeof t&&(t=t.replace(/rgba?\(/,"").replace(/\)/,"").split(","),e.each(t,function(e,o){t[e]=+o})),"string"==typeof o&&(o=o.replace(/rgba?\(/,"").replace(/\)/,"").split(","),e.each(o,function(e,t){o[e]=+t})),"object"==typeof t&&t.hasOwnProperty("length")&&3==t.length&&t.push(1),"object"==typeof o&&o.hasOwnProperty("length")&&3==o.length&&o.push(1);var a=[0,0,0,0];return a[3]=1-(1-o[3])*(1-t[3]),0===a[3]&&(a[3]=1e-6),a[0]=Math.min(o[0]*o[3]/a[3]+t[0]*t[3]*(1-o[3])/a[3],255),a[1]=Math.min(o[1]*o[3]/a[3]+t[1]*t[3]*(1-o[3])/a[3],255),a[2]=Math.min(o[2]*o[3]/a[3]+t[2]*t[3]*(1-o[3])/a[3],255),e.map(a,function(e){return Math.floor(e)})}},p=function(e,t){return u(e||[255,255,255,1],t||[255,255,255,1])},C=function(e,t){var o=p(e,t);return Math.round((.2126*+o[0]+.7152*+o[1]+.0722*+o[2])/2.55)/100},v=function(t){void 0!==t&&(t>.6?e(".header-wrapper").addClass("light").removeClass("dark"):e(".header-wrapper").addClass("dark").removeClass("light"))},b=function(){e(window).ready(function(){e(".post").each(function(t,o){var a=e(o),i=a.find(".post-header").height();a.find(".post-content").css("min-height",i)})})},y=function(){e(document).ready(function(){e(".comment-form").hasClass("form_with_errors")?e("html, body").scrollTop(e(".comment-form").offset().top):e("form").find(".form_error, .form_notice").length>0&&e("html, body").scrollTop(e(".form_error, .form_notice").closest("form").offset().top)})},w=function(e){(e=void 0!==e&&e)&&j({stickyHeader:!0,stickyMobileMenu:!0,stickyFooter:!1,stickyPostHeaders:!1})},x=function(t){t=void 0!==t&&t,t&&j({stickyHeader:!0,stickyMobileMenu:!0,stickyFooter:!1,stickyPostHeaders:!1}),e.fn.autogrow&&e(".form_field_textarea").autogrow(),e(window).ready(function(){e.trim(e(".content-header").get(0).innerHTML)||e(".content-header").hide()})},k=function(t){t=void 0!==t&&t,t&&j({stickyHeader:!0,stickyMobileMenu:!0,stickyFooter:!1,stickyPostHeaders:!1}),e.fn.autogrow&&e(".form_field_textarea").autogrow()},_=function(e){e=void 0!==e&&e,e&&j({stickyHeader:!0,stickyMobileMenu:!0,stickyFooter:!0,stickyPostHeaders:!0}),b()},j=function(t){var o,a,i,s,n=t.stickyHeader||!1,r=t.stickyMobileMenu||!1,d=t.stickyFooter||!1,l=t.stickyPostHeaders||!1,c=e(".container"),g=e(".header"),h=e(".footer"),m=e(g).height()+90,f=e(h).height()+90,u=0,p=!1,C=function(){var t=e(".post"),o=[];return t.each(function(e,t){o.push(t.getBoundingClientRect().top)}),o},v=function(t){o?(a=e(window).scrollTop(),i=a-o,window.innerWidth<640&&r&&(i>5&&o>m?e(".topbar").addClass("fixed").css({top:-m}):i<-5&&o>m?e(".topbar").addClass("fixed").css({top:0}):i<0&&o<=100&&!0===e(".topbar").hasClass("fixed")&&(e(c).css({"margin-top":0}),e(".topbar").removeClass("fixed"))),window.innerWidth>640&&d&&(e(".post").eq(0).offset().top-e(window).innerHeight()+90<e(document).scrollTop()&&o+window.innerHeight<=e(document).height()-f-40?i<-5?_(!1):i>5&&x():k()),n&&e(g).find(".header-inner").height()<60&&(i>5&&o>m?b():i<-5&&o>m?(y(),setTimeout(function(){e(window).scrollTop()<=m&&w()},20)):i<-5&&o<=m&&w()),o=0):o=e(window).scrollTop(),window.innerWidth>640&&l&&e(".post").each(function(o,a){var i=e(a).find(".post-header"),s=-(e(a).height()-30-i.height());t[o]<30?t[o]>s?(i.removeClass("top bottom"),e(a).addClass("fixed-header")):(i.addClass("bottom").removeClass("top"),e(a).removeClass("fixed-header")):(i.addClass("top").removeClass("bottom"),e(a).removeClass("fixed-header"))})},b=function(){e(g).addClass("header-fixed").css({top:-m}),e(c).css({"padding-top":m})},y=function(){var t;t=e("body").hasClass("edy-checkout-button-visible")?e(".edy-ecommerce-shopping-cart-button").outerHeight():0,e(g).addClass("header-fixed header-animated").css({top:t}),e(c).css({"padding-top":m})},w=function(){e(g).removeClass("header-fixed header-animated"),e(c).css({"padding-top":0}),e(".post.fixed-header").removeClass("fixed-header")},x=function(){e(h).addClass("footer-fixed footer-animated footer-hidden"),e(h).css("bottom",-e(h).outerHeight())},k=function(){e(h).removeClass("footer-fixed footer-animated footer-hidden"),e("body").removeClass("voog-search-visible"),e(h).css({bottom:"",left:""}),e(c).css({"margin-bottom":""})},_=function(t){t=t||!1,e(h).addClass("footer-fixed footer-animated"),e(h).css({left:e(".container").offset().left,bottom:t?0:60-e(h).height()}),e(c).css({"margin-bottom":f})},j=function(t){t?e(h).hasClass("footer-fixed")&&(clearTimeout(s),_(!0),e("footer .gradient-overlay").hide()):e("footer").hasClass("footer-fixed")&&(s=setTimeout(function(){_(!1),e("footer .gradient-overlay").show()},1500))},B=function(){u=window.scrollY,A()},A=function(){p||requestAnimationFrame(P),p=!0},P=function(){p=!1,e(window).width()>640&&v(C())};e(window).on("load resize",function(){e(window).width()>640?v(C()):(e(".container").css({"padding-top":"","margin-bottom":""}),e(".header-fixed").removeClass("header-fixed header-animated").css("top",""))}).on("scroll",B),e("footer").bind("mouseenter",function(){j(!0)}).bind("mouseleave",function(){j(!1)})},B=function(e){window.edy=window.edy||[],edy.push(["texteditorStyles",{name:e,tagname:"a",attribute:{href:"#"},classname:"custom-btn",toggle:!0}])},A=function(){o()||S()},P=function(t){"show_product_related_pages_in_main_menu"in t||(t.show_product_related_pages_in_main_menu=!1),e(".js-root-item-settings-toggle").each(function(o,a){new Edicy.SettingsEditor(a,{menuItems:[{titleI18n:"show_in_main_menu",type:"checkbox",key:"show_product_related_pages_in_main_menu",states:{on:!0,off:!1}}],buttonTitleI18n:"settings",values:t,containerClass:["js-root-item-settings-popover","js-prevent-sideclick"],preview:function(t){!0==!t.show_product_related_pages_in_main_menu?e(".js-menu-item-products").addClass("is-hidden"):e(".js-menu-item-products").removeClass("is-hidden")},commit:function(e){siteData.set("settings_root_item",e)}})})},I=function(t){e(".js-content-item-img-drop-area").each(function(o,a){var i=e(a),s=i.closest(".js-content-item-box"),n=s.data("item-id"),r=s.data("item-type");new Edicy.CustomData({type:r,id:n}),new Edicy.ImgDropArea(i,{positionable:!1,target_width:1280,placeholder:'<div class="edy-img-drop-area-placeholder">'+t+"</div>",removeBtn:'<div class="edy-img-drop-area-remove-image"><div class="edy-img-drop-area-remove-image-ico"><svg width="16" height="20" viewBox="0 0 26 30" xmlns="http://www.w3.org/2000/svg"><g fill-rule="nonzero" fill="currentColor"><g transform="translate(2 5)"><path d="M0 .997h2V21c0 1 1 2 2 2h14c1 0 2-1 2-2V1h2v20c0 2.25-1.75 4-4 4H4c-2.25 0-4-1.75-4-4V.997z"/><rect x="10" y="4" width="2" height="16" rx="1"/><rect x="5" y="4" width="2" height="16" rx="1"/><rect x="15" y="4" width="2" height="16" rx="1"/></g><path d="M26 4v2H0V4h7V2c0-1 1-2 2-2h8c1 0 2 1 2 2v2h7zM9 4h8V3c0-.5-.5-1-1-1h-6c-.5 0-1 .5-1 1v1z"/></g></svg></div></div>',change:function(e){var t;i.removeClass("is-cropped").addClass("not-cropped").css("opacity",.1),e?(t=e.original_id,s.removeClass("without-image is-loaded with-error").addClass("with-image not-loaded"),M(s,e.width,e.height)):(t=null,s.removeClass("with-image is-loaded with-error").addClass("without-image not-loaded"),s.find(".edy-img-drop-area-placeholder").css("opacity",0)),H(s,i,n,t,r)}})})},M=function(e,t,o){var a=e.find(".js-content-item-img-drop-area"),i=e.find(".js-toggle-crop-state");t>o?a.removeClass("image-landscape image-square image-portrait").addClass("image-landscape"):t===o?a.removeClass("image-landscape image-square image-portrait").addClass("image-square"):a.removeClass("image-landscape image-square image-portrait").addClass("image-portrait"),a.hasClass("image-square")?i.removeClass("is-visible").addClass("is-hidden"):i.removeClass("is-hidden").addClass("is-visible")},H=function(t,o,a,i,s){var n="article"===s?"articles":"pages",r=new Edicy.CustomData({type:s,id:a});e.ajax({type:"PATCH",contentType:"application/json",url:"/admin/api/"+n+"/"+a,data:JSON.stringify({image_id:i}),dataType:"json",success:function(e){r.set("image_crop_state","not-cropped"),t.removeClass("not-loaded with-error").addClass("is-loaded"),t.find(".edy-img-drop-area-placeholder").css("opacity",1),o.css("opacity",1)},timeout:3e4,error:function(e){t.removeClass("not-loaded is-loaded with-error").addClass("with-error")}})},T=function(){e(".js-toggle-crop-state").on("click",function(){var t,o=e(this).closest(".js-content-item-box"),a=o.find(".js-content-item-img-drop-area"),i=o.data("item-id"),s=o.data("item-type"),n=new Edicy.CustomData({type:s,id:i});a.hasClass("is-cropped")?(a.removeClass("is-cropped").addClass("not-cropped"),t="not-cropped"):(a.removeClass("not-cropped").addClass("is-cropped"),t="is-cropped"),n.set("image_crop_state",t)})},S=function(){e(document).ready(function(){setTimeout(function(){e(".js-content-item-box").addClass("not-loaded")},3e3)}),e(".js-lazyload").lazyload({threshold:500,effect:"fadeIn",placeholder:"data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==",load:function(){var t=e(this).closest(".js-content-item-box");t.removeClass("not-loaded with-error").addClass("is-loaded"),setTimeout(function(){t.removeClass("not-loaded with-error"),t.find(".js-loader").remove()},3e3)}})},o=function(){return e("html").hasClass("editmode")};window.site=e.extend(window.site||{},{initFrontPage:w,initCommonPage:x,initBlogPage:_,initArticlePage:k,toggleFlags:a,getImageByWidth:c,headerBgPreview:m,headerBgCommit:f,initItemsPage:A,handleHeaderColorScheme:v,bindCustomTexteditorStyles:B,bindRootItemSettings:P,bindContentItemImgDropAreas:I,bindContentItemImageCropToggle:T,bindSiteSearch:t}),function(){n(),r(),d(),l(),s(),y(),e(".content form").edicyFormPlaceholders(),!Modernizr.flexbox&&o&&i()}()}(jQuery);
// requestAnimationFrame polyfill by Erik Möller. fixes from Paul Irish and Tino Zijdel
// MIT license
(function() {
  var lastTime = 0;
  var vendors = ['ms', 'moz', 'webkit', 'o'];
  for(var x = 0; x < vendors.length && !window.requestAnimationFrame; ++x) {
    window.requestAnimationFrame = window[vendors[x]+'RequestAnimationFrame'];
    window.cancelAnimationFrame = window[
      vendors[x]+'CancelAnimationFrame'
    ] || window[
      vendors[x]+'CancelRequestAnimationFrame'
    ];
  }

  if (!window.requestAnimationFrame)
    window.requestAnimationFrame = function(callback, element) {
      var currTime = new Date().getTime();
      var timeToCall = Math.max(0, 16 - (currTime - lastTime));
      var id = window.setTimeout(function() { callback(currTime + timeToCall); },
        timeToCall);
      lastTime = currTime + timeToCall;
      return id;
    };

  if (!window.cancelAnimationFrame)
    window.cancelAnimationFrame = function(id) {
      clearTimeout(id);
    };
}());
